/** English copy for the extension, keyed by the Swedish source string. */
export const EN: Record<string, string> = {
  // side panel
  "Laddar…": "Loading…",
  "Kunde inte nå servern: {m}": "Could not reach the server: {m}",
  "Försök igen": "Try again",
  "Provperiod · {n} dagar kvar": "Trial · {n} days left",
  "Månad": "Monthly",
  "3 månader": "3 months",
  "Ingen aktiv plan": "No active plan",
  "Mina CV": "My CVs",
  "Byt CV": "Replace CV",
  "Tilläggets källkod (AGPL-3.0)": "Extension source code (AGPL-3.0)",
  "Källkod": "Source",
  "Logga ut": "Log out",
  "Välj plan för att komma igång": "Choose a plan to get started",
  "De första 7 dagarna är gratis. Sedan 99 kr/mån eller 199 kr för 3 månader. Avsluta när du vill.": "The first 7 days are free. Then 99 kr/month or 199 kr for 3 months. Cancel anytime.",
  "Välj plan": "Choose a plan",
  "Öppna en annons": "Open a job ad",
  "Gå till en annons på Platsbanken eller Indeed så anpassar Meritio ditt CV till den.": "Go to a job ad on Platsbanken or Indeed and Meritio adapts your CV to it.",
  "Vald annons på Indeed": "Selected ad on Indeed",
  "Annons på Platsbanken": "Ad on Platsbanken",
  "Klicka när du vill anpassa ditt CV till den här annonsen.": "Click when you want to adapt your CV to this ad.",
  "Anpassa CV till annonsen": "Adapt CV to this ad",
  "Annons": "Job ad",
  "Läser annonsen…": "Reading the ad…",
  "Matchning": "Match",
  "av {n} krav": "of {n} requirements",
  " · {n} tillagda": " · {n} added",
  "I ditt CV: {e}": "In your CV: {e}",
  "ändring": "change",
  "ändringar": "changes",
  "delvis": "partial",
  "saknas": "missing",
  "Läser annonsen": "Reading the ad",
  "Jämför med ditt CV": "Comparing with your CV",
  "Skriver förslag": "Writing suggestions",
  "Inga ändringar föreslagna. Ditt CV täcker annonsen bra som det är.": "No changes suggested. Your CV covers the ad well as it is.",
  "Granska ändringar · fler på väg": "Review changes · more coming",
  "Granska ändringar": "Review changes",
  "Svenska": "Swedish",
  "English": "English",

  // login
  "Inloggningen avbröts": "Sign-in was cancelled",
  "Inga tokens i svaret": "No tokens in the response",
  "Logga in": "Log in",
  "Skapa konto": "Create account",
  "Fortsätt där du slutade.": "Pick up where you left off.",
  "Ditt CV lagras krypterat i EU.": "Your CV is stored encrypted in the EU.",
  "Fortsätt med Google": "Continue with Google",
  "eller med e-post": "or with email",
  "E-post": "Email",
  "Lösenord": "Password",
  "Vänta…": "Please wait…",
  "Inget konto?": "No account?",
  "Skapa ett": "Create one",
  "Har du konto?": "Have an account?",

  // upload
  "Bara Word-filer (.docx). Har du PDF? Öppna den i Word eller Google Docs och spara som .docx.": "Word files only (.docx). Only have a PDF? Open it in Word or Google Docs and save as .docx.",
  "Ladda upp ditt CV": "Upload your CV",
  "Som Word-fil. Vi ändrar bara texten, aldrig layout, typsnitt eller färger.": "As a Word file. We only change the text, never layout, fonts or colours.",
  "Läser in ditt CV…": "Reading your CV…",
  "Välj Word-fil (.docx)": "Choose Word file (.docx)",
  "Tar ungefär tio sekunder": "Takes about ten seconds",
  "eller släpp filen här": "or drop the file here",
  "Avbryt": "Cancel",
  "Har du bara PDF? Öppna den i Word eller Google Docs och spara som .docx.": "Only have a PDF? Open it in Word or Google Docs and save as .docx.",
  "Ditt CV är sparat": "Your CV is saved",
  "Dokumentet sparas som det är. Det här hittade vi i det:": "The document is stored as is. This is what we found in it:",
  "Namn saknas": "Name missing",
  "{n} anställningar med {b} punkter": "{n} positions with {b} bullet points",
  "{n} kompetenser": "{n} skills",
  "{n} utbildningar": "{n} education entries",
  "Profiltext": "Summary",
  "Ingen profiltext": "No summary",
  "Klar": "Done",
  "Visa mitt CV": "View my CV",
  "Annan fil": "Another file",

  // my cvs
  "← Tillbaka": "← Back",
  "Inga nedladdade CV än": "No downloaded CVs yet",
  "Varje CV du laddar ner från en annons hamnar här.": "Every CV you download from an ad ends up here.",
  "Hämtar…": "Fetching…",
  "Ladda ner {f}": "Download {f}",
  "Annonsen": "The ad",
  "Ta bort": "Remove",
  "annons": "ad",

  // review page
  "Kunde inte hämta ditt CV: {m}": "Could not fetch your CV: {m}",
  "Kunde inte läsa dokumentets stycken: {m}": "Could not read the document's paragraphs: {m}",
  "Ingen anpassning hittades. Klicka på Meritio-knappen på en annons först.": "No adaptation found. Click the Meritio button on a job ad first.",
  "Visa annonsens krav": "Show the ad's requirements",
  "{c} av {t} krav": "{c} of {t} requirements",
  " · tillagt": " · added",
  "Fler förslag på väg…": "More suggestions coming…",
  "{n} öppna ändringar": "{n} open changes",
  "Inga öppna ändringar": "No open changes",
  "Acceptera alla spårade ändringar i dokumentet": "Accept all tracked changes in the document",
  "Acceptera alla": "Accept all",
  "Ladda ner Word": "Download Word",
  "Ladda ner PDF": "Download PDF",
  "Stäng (Esc)": "Close (Esc)",
  "Förslagen ligger som spårade ändringar i texten, med motiveringen i bubblan. Acceptera eller avvisa dem där. Det du skriver själv spåras på samma sätt.": "The suggestions are tracked changes in the text, with the reasoning in the bubble. Accept or reject them there. What you type yourself is tracked the same way.",
  "Öppnar ditt CV…": "Opening your CV…",
  "Uppdaterar dokumentet…": "Updating the document…",
  "Kunde inte öppna dokumentet: {m}": "Could not open the document: {m}",
  "Förslag för {p} kunde inte placeras: texten hittades inte.": "Suggestion for {p} could not be placed: the text was not found.",
  "Förslag för {p} kunde inte placeras.": "Suggestion for {p} could not be placed.",
  "Kunde inte placera raden för \"{r}\": hittar ingen plats i dokumentet.": "Could not place the line for \"{r}\": no place found in the document.",
  "Kunde inte placera raden för \"{r}\": stycket hittades inte.": "Could not place the line for \"{r}\": the paragraph was not found.",
  "Kunde inte placera raden för \"{r}\": slutet av stycket hittades inte.": "Could not place the line for \"{r}\": the end of the paragraph was not found.",
  "Raden för \"{r}\" kunde inte läggas in.": "The line for \"{r}\" could not be inserted.",
  "Från ditt svar. Annonsen efterfrågar: {r}.": "From your answer. The ad asks for: {r}.",
  "På din begäran: {n}": "At your request: {n}",
  "Motivering: ": "Reason: ",
  "Lyfter fram {a}": "Brings forward {a}",
  "tonar ner {r}": "tones down {r}",

  // chat
  "Vilka krav saknar jag helt?": "Which requirements am I missing entirely?",
  "Gör profiltexten kortare": "Make the summary shorter",
  "Jag har mer erfarenhet som inte står i CV:t": "I have more experience that isn't in my CV",
  "Angående \"{r}\" (Placering: {p}): {m}": "Regarding \"{r}\" (Placement: {p}): {m}",
  "Placering: {p}": "Placement: {p}",
  "({n} ändring kunde inte placeras i dokumentet.)": "({n} change could not be placed in the document.)",
  "({n} ändringar kunde inte placeras i dokumentet.)": "({n} changes could not be placed in the document.)",
  "{r} – var i ditt CV hör det hemma?": "{r} – where in your CV does it belong?",
  "Okej, under Kompetenser. Vad ska stå? Ett eller två ord räcker, t.ex. \"{r}\".": "Okay, under Skills. What should it say? One or two words are enough, e.g. \"{r}\".",
  "Okej, i profilen. Skriv en kort mening om det, så lägger jag in den.": "Okay, in the summary. Write a short sentence about it and I'll add it.",
  "Okej, under {l}. Vad gjorde du? En rad räcker, så skriver jag den i din stil.": "Okay, under {l}. What did you do? One line is enough, I'll write it in your style.",
  "Kompetenser": "Skills",
  "Profil": "Summary",
  "Stäng": "Close",
  "Stäng chatten": "Close the chat",
  "Annonsen efterfrågar en sak som inte syns i ditt CV. Har du det? Klicka och berätta kort, så skriver jag raden i din stil.": "The ad asks for one thing that isn't visible in your CV. Do you have it? Click and tell me briefly, and I'll write the line in your style.",
  "Annonsen efterfrågar {n} saker som inte syns i ditt CV. Har du det? Klicka och berätta kort, så skriver jag raden i din stil.": "The ad asks for {n} things that aren't visible in your CV. Do you have them? Click and tell me briefly, and I'll write the line in your style.",
  "Be om ändringar, ställ frågor, eller berätta om erfarenhet som inte står i CV:t. Ändringar visas som spårade ändringar i dokumentet.": "Ask for changes, ask questions, or tell me about experience that isn't in your CV. Changes appear as tracked changes in the document.",
  "Öppna chatten": "Open the chat",
  "Fråga Meritio eller be om en ändring…": "Ask Meritio or request a change…",
  "Skicka": "Send",

  // content scripts
  "Meritio tittar på den här annonsen": "Meritio is looking at this ad",
  "Annons på Indeed": "Ad on Indeed",
};
